/**
 * Deborah — Transcript PDF export builder (AUTH A-12 §13)
 * ------------------------------------------------------
 * Minimal, dependency-free PDF 1.4 generator for the transcript table:
 * semestr, fan, baho, kredit. No fonts are embedded — the standard
 * Helvetica (Type1, WinAnsiEncoding) is used, so text is transliterated
 * to ASCII (UZ/Cyrillic → Latin). Suitable for a human-readable export,
 * not for archival-grade Unicode PDF.
 *
 * Safety: only static text objects — no scripts, no attachments, no
 * external references (guards against PDF-embedded active content).
 */

// ── ASCII transliteration (uz-Latn + Cyrillic → ASCII) ──────────────
const CYR_MAP = {
  а: 'a', б: 'b', в: 'v', г: 'g', д: 'd', е: 'e', ё: 'e', ж: 'zh', з: 'z',
  и: 'i', й: 'y', к: 'k', л: 'l', м: 'm', н: 'n', о: 'o', п: 'p', р: 'r',
  с: 's', т: 't', у: 'u', ф: 'f', х: 'kh', ц: 'ts', ч: 'ch', ш: 'sh',
  щ: 'sch', ъ: '', ы: 'y', ь: '', э: 'e', ю: 'yu', я: 'ya',
  ў: 'o', қ: 'q', ғ: 'g', ҳ: 'h', ж: 'zh', '’': "'",
};

export function toAscii(input) {
  let s = String(input ?? '');
  s = s.replace(/[ʻ‘’`'']/g, "'").replace(/…/g, '...').replace(/[—–]/g, '-').replace(/["“”«»]/g, '"');
  return s
    .split('')
    .map((ch) => {
      const lower = ch.toLowerCase();
      const mapped = CYR_MAP[lower];
      if (mapped !== undefined) {
        return ch === lower ? mapped : mapped.charAt(0).toUpperCase() + mapped.slice(1);
      }
      return ch;
    })
    .join('')
    .replace(/[^\x20-\x7E]/g, '?');
}

/** Escape a PDF literal string. */
function pdfString(str) {
  return toAscii(str).replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

/**
 * Build a transcript PDF buffer.
 * @param {object} opts
 * @param {Array<{semester:string, subject:string, grade:string, credit:string}>} opts.rows
 * @param {string} [opts.studentName]
 * @param {string} [opts.title]
 * @param {string} [opts.institution='Deborah']
 */
export function buildTranscriptPdf({ rows = [], studentName = '', title = 'Transkript', institution = 'Deborah' }) {
  const PAGE_W = 595; // A4 portrait
  const PAGE_H = 842;
  const LINE_H = 16;
  const HEADER_H = 22;
  const TOP = PAGE_H - 48;

  const safeRows = (rows || []).map((r) => ({
    semester: toAscii(r.semester || ''),
    subject: toAscii(r.subject || ''),
    grade: toAscii(r.grade || ''),
    credit: toAscii(r.credit || ''),
  }));

  // Split into pages of ~44 rows
  const perPage = 44;
  const pages = [];
  for (let i = 0; i < Math.max(1, Math.ceil(safeRows.length / perPage)); i++) {
    pages.push(safeRows.slice(i * perPage, (i + 1) * perPage));
  }

  // Object layout (ids = array index + 1):
  //   1 catalog, 2 pages, 3 F1 (Helvetica), 4 F2 (Helvetica-Bold),
  //   5 + p*2 page p, 6 + p*2 content stream p.
  // Fonts are pushed BEFORE the pages so page resources reference fixed ids.
  const objects = [];
  const firstPageId = 5;
  const kidRefs = pages.map((_, i) => `${firstPageId + i * 2} 0 R`).join(' ');
  objects.push('<< /Type /Catalog /Pages 2 0 R >>'); // 1
  objects.push(`<< /Type /Pages /Kids [${kidRefs}] /Count ${pages.length} >>`); // 2
  objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'); // 3 (F1)
  objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>'); // 4 (F2)

  for (let p = 0; p < pages.length; p++) {
    objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_W} ${PAGE_H}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${firstPageId + p * 2 + 1} 0 R >>`); // page obj
    const pageRows = pages[p];
    const lines = [];
    let y = TOP - 8;
    lines.push('BT /F2 16 Tf 48 ' + y + ' Td (' + pdfString(title) + ') Tj ET');
    y -= 14;
    lines.push('BT /F1 9 Tf 48 ' + y + ' Td (' + pdfString(institution + ' - ' + studentName) + ') Tj ET');
    y -= 22;

    // Table header
    const cols = [48, 120, 420, 500, 545]; // semester, subject, grade, credit boundaries
    const headPos = [
      { x: cols[0], text: 'Semestr' },
      { x: cols[1], text: 'Fan' },
      { x: cols[3], text: 'Baho' },
      { x: cols[4], text: 'Kredit' },
    ];
    lines.push('BT /F1 10 Tf 0.2 0.25 0.5 rg ' + headPos.map((h) => `${h.x} ${y} Td (${pdfString(h.text)}) Tj`).join(' ') + ' ET');
    lines.push(`0.6 0.6 0.6 RG 48 ${y - 3} m 545 ${y - 3} l S`);
    y -= HEADER_H;

    for (const row of pageRows) {
      lines.push(`BT /F1 9 Tf 0 0 0 rg ${cols[0]} ${y} Td (${pdfString(row.semester)}) Tj ${cols[1] - cols[0]} 0 Td (${pdfString(row.subject)}) Tj ${cols[3] - cols[1]} 0 Td (${pdfString(row.grade)}) Tj ${cols[4] - cols[3]} 0 Td (${pdfString(row.credit)}) Tj ET`);
      y -= LINE_H;
      if (y < 60) break; // safety
    }
    lines.push('BT /F1 8 Tf 48 40 Td (Generated by Deborah - evidence portfolio) Tj ET');

    const content = lines.join('\n');
    objects.push(`<< /Length ${Buffer.byteLength(content, 'utf8')} >>\nstream\n${content}\nendstream`); // contents obj
  }

  // Assemble
  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  for (let i = 0; i < objects.length; i++) {
    offsets.push(Buffer.byteLength(pdf, 'utf8'));
    pdf += `${i + 1} 0 obj\n${objects[i]}\nendobj\n`;
  }
  const xrefStart = Buffer.byteLength(pdf, 'utf8');
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';
  for (let i = 1; i <= objects.length; i++) {
    pdf += String(offsets[i]).padStart(10, '0') + ' 00000 n \n';
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;

  return Buffer.from(pdf, 'utf8');
}
